baseURL = "https://nataphet.github.io/"
languageCode = "en-us"
title = "Nata Phet"
themesDir = "themes"
theme = "nata"

#for comment
disqusShortname = "sewuhardware-github-io"

#front-matter pakai format yaml
MetaDataFormat = "yaml"

# Untuk deskripsi tag meta di homepage
description = "Personal blog berisi catatan tentang IT"

# kanggo URL supaya home/artikel
[permalinks]
  artikel = "/:title/"

[taxonomies]
  category= "kategori"
  series= "tutorial"
  tag= "topik"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[author]
    name = "Nata Phet"
    homepage = "https://twitter.com/nataphet"
    bio = "Belajar menjadi manusia..."
    image = "https://lh3.googleusercontent.com/-AoP_JyoYu8s/Tm2LQHqd47I/AAAAAAAAAAg/MXGKKAjhIMYxwHXQ25oVWNbeJu5xbjXWACEwYBhgL/w140-h140-p/34.jpg"


[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Networking"
    link   = "tutorial/networking/"

[[params.menu]]
    before = false
    label  = "Oprek"
    link   = "tutorial/oprek/"

[[params.menu]]
    before = false
    label  = "eBook"
    link   = "tutorial/ebook/"


# Enable and disable widgets sidebar sebelah kanan
[params.widgets]
    artikel_terbaru = true
    kategori = true
    topik = true

    iklan = true
    iklan_300 = true
    iklan_125_1 = false
    iklan_125_2 = false
    iklan_125_3 = false
    iklan_125_4 = false        


    